import { NextRequest, NextResponse } from 'next/server';
import { Octokit } from '@octokit/rest';

export async function POST(request: NextRequest) {
  try {
    const { productName, buildPrompt, productSpec } = await request.json();

    const token = process.env.GITHUB_TOKEN;
    if (!token) {
      return NextResponse.json(
        { error: 'GITHUB_TOKEN not configured. Please add your GitHub personal access token to .env.local' },
        { status: 500 }
      );
    }

    const octokit = new Octokit({ auth: token });

    // Get authenticated user
    const { data: user } = await octokit.users.getAuthenticated();

    // Create repository name from product name
    const repoName = productName
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');

    // Create the repository
    const { data: repo } = await octokit.repos.createForAuthenticatedUser({
      name: repoName,
      description: `Generated by PromptForge`,
      private: false,
      auto_init: true
    });

    // Create README.md
    await octokit.repos.createOrUpdateFileContents({
      owner: user.login,
      repo: repoName,
      path: 'README.md',
      message: 'Add product specification',
      content: Buffer.from(productSpec).toString('base64')
    });

    // Wait a moment for the initial commit to complete
    await new Promise(resolve => setTimeout(resolve, 1000));

    // Create BUILD_PROMPT.md
    await octokit.repos.createOrUpdateFileContents({
      owner: user.login,
      repo: repoName,
      path: 'BUILD_PROMPT.md',
      message: 'Add build prompt for Claude Code',
      content: Buffer.from(buildPrompt).toString('base64')
    });

    return NextResponse.json({
      success: true,
      repoUrl: repo.html_url,
      repoName: repo.full_name
    });
  } catch (error: any) {
    console.error('GitHub API error:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to create GitHub repository' },
      { status: 500 }
    );
  }
}
